### ISSUE TITLE
Explore how to use the ISM features from another plugin

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer-plugins#12]
## Description

The initialization plugin needs to ensure that the index templates, indices and ISM policies are created during startup.

In the Spike, we demonstrated how to create an index using custom mappings and settings, but not how to do the same with the Index Templates or the ISM policies. This issue aims to close this gap. 

> We need to explore **how to create index templates** (using the Index Management plugin), as a way to overcome the problems stated above. The strategy of creating single indices with mappings and settings only works for that particular index, and won't apply to rotated stream indices.

OpenSearch Playground has 2 composable index templates. Searching the name `.opensearch-sap-detectors-queries-index-template`, I found out there is an API at [`opensearch.admin.indices.template.put`](https://github.com/opensearch-project/OpenSearch/tree/dfb8449ed8f85e0c1e8601c86d17b833e1641e0f/server/src/main/java/org/opensearch/action/admin/indices/template/put).

1. [playground.opensearch.org](https://playground.opensearch.org/app/opensearch_index_management_dashboards#/templates?dataSourceId=&from=0&search=&size=20&sortDirection=desc&sortField=name)
2. [DetectorMonitorConfig.java#L22](https://github.com/opensearch-project/security-analytics/blob/16bcef3b398f7c20d73d34d03bde80bc4ce1b421/src/main/java/org/opensearch/securityanalytics/config/monitors/DetectorMonitorConfig.java#L22)
3. [RuleTopicIndices.java#L16](https://github.com/opensearch-project/security-analytics/blob/16bcef3b398f7c20d73d34d03bde80bc4ce1b421/src/main/java/org/opensearch/securityanalytics/util/RuleTopicIndices.java#L16)
4. [PutComposableIndexTemplateAction.java#L61](https://github.com/opensearch-project/OpenSearch/blob/dfb8449ed8f85e0c1e8601c86d17b833e1641e0f/server/src/main/java/org/opensearch/action/admin/indices/template/put/PutComposableIndexTemplateAction.java#L61)

_Originally posted by @AlexRuiz7 in https://github.com/wazuh/wazuh-indexer-plugins/issues/11#issuecomment-2221627353_
            

## Tasks

- [x] Explore how to create index templates programmatically
- [ ] Explore how to create composable index templates programmatically
- [ ] Explore how to create ISM policies programmatically
- [ ] Explore how to create stuff above from JSON files (same format as using the REST API)
- [ ] Add functionality to the plugin

**Comment by AlexRuiz7** [comment]
About composable index templates (index templates v2), OpenSearch playground has an index template which is created programmatically by a plugin.

![image](https://github.com/user-attachments/assets/b6a59bff-39e3-48e0-a457-c62464bbcee0)


* https://github.com/opensearch-project/security-analytics/blob/main/src/main/java/org/opensearch/securityanalytics/util/RuleTopicIndices.java#L69
* https://github.com/search?q=org%3Aopensearch-project+%22new+ComposableIndexTemplate%22&type=code
* https://github.com/opensearch-project/OpenSearch/blob/451606535752a73be80d5203ae417e7d57fc5cef/server/src/internalClusterTest/java/org/opensearch/indices/template/ComposableTemplateIT.java#L69
* https://github.com/opensearch-project/OpenSearch/blob/451606535752a73be80d5203ae417e7d57fc5cef/server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java#L694

**Comment by AlexRuiz7** [comment]
Moved to the Feature Complete stage.

**Comment by AlexRuiz7** [comment]
Superseded by https://github.com/wazuh/wazuh-indexer-plugins/issues/12
