### ISSUE TITLE
Support new stage Alpha 2 for 4.9.0 in wazuh-indexer-plugins repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-indexer-plugins#15]
## Description

This issue attempts to support a new stage Alpha 2 for 4.9.0 in the wazuh-indexer-plugins repository.

## Tasks

- [ ] Ensure changelog is updated for 4.9.0 (if applicable).
- [ ] Bump revision for branch 4.9.0 on wazuh-indexer-plugins repository.
- [ ] Create tag v4.9.0-alpha2 from branch 4.9.0 on wazuh-indexer-plugins repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-indexer-plugins/releases/tag/v4.9.0-alpha2.

**Comment by AlexRuiz7** [comment]
This repo is not in use until 5.0.0
