### ISSUE TITLE
Implement stateful (inventory) indexes creation

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer-plugins#41]
## Description

Include the latest version of the stateful indexes templates to the wazuh-setup plugin.

#### states-fim

- [x] https://github.com/wazuh/wazuh-indexer/issues/396
- [x] https://github.com/wazuh/wazuh-indexer-plugins/issues/46

#### states-inventory-networks

- [x] wazuh/wazuh-indexer#535
- [x] #138

#### states-inventory-ports

- [x] wazuh/wazuh-indexer#536
- [x] #139

#### states-inventory-hardware

- [x] wazuh/wazuh-indexer#537
- [x] #140

#### states-inventory-hotfixes

- [x] wazuh/wazuh-indexer#538
- [x] #141

#### states-inventory-packages

- [x] https://github.com/wazuh/wazuh-indexer/issues/398
- [x] https://github.com/wazuh/wazuh-indexer-plugins/issues/47

#### states-inventory-processes

- [x] https://github.com/wazuh/wazuh-indexer/issues/400
- [x] https://github.com/wazuh/wazuh-indexer-plugins/issues/48

#### states-inventory-system

- [x] https://github.com/wazuh/wazuh-indexer/issues/402
- [x] https://github.com/wazuh/wazuh-indexer-plugins/issues/49

#### states-vulnerabilities

- [x] https://github.com/wazuh/wazuh-indexer/issues/404
- [x] https://github.com/wazuh/wazuh-indexer-plugins/issues/50
