### ISSUE TITLE
Support new stage RC 1 for 4.8.1 in wazuh-indexer-plugins repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-indexer-plugins#5]
## Description

This issue attempts to support a new stage RC 1 for 4.8.1 in the wazuh-indexer-plugins repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.1 (if applicable).
- [ ] Bump revision for branch 4.8.1 on wazuh-indexer-plugins repository.
- [ ] Create tag v4.8.1-rc1 from branch 4.8.1 on wazuh-indexer-plugins repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-indexer-plugins/releases/tag/v4.8.1-rc1.
